version: "2.4"
services:
  postgres:
    image: postgres:10.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=kong
      - POSTGRES_USER=kong
    healthcheck:
      test: ["CMD", "pg_isready"]
      start_period: 3s
      timeout: 5s
      retries: 3
  
  cassandra:
    image: cassandra:3.11
    restart: unless-stopped
    environment:
      - CASSANDRA_CLUSTER_NAME=kong
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=RACK1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    healthcheck:
      test: ["CMD", "cqlsh", "cassandra"]
      start_period: 5s
      timeout: 5s
      retries: 3

  migrator:
    build: .
    image: rucciva/kong-plugin-oauth2-token-audience
    restart: on-failure
    depends_on: 
      postgres:
        condition: service_healthy
      cassandra:
        condition: service_healthy
    environment:
      - KONG_PG_HOST=postgres
      - KONG_PG_DATABASE=kong
      - KONG_CASSANDRA_CONTACT_POINTS=cassandra
      - KONG_CASSANDRA_DATA_CENTERS=DC1:1
      - KONG_CASSANDRA_REPL_STRATEGY=NetworkTopologyStrategy
      - KONG_CASSANDRA_LOCAL_DATACENTER=DC1
    command: 
      - /bin/bash 
      - -c 
      - KONG_DATABASE=postgres kong migrations bootstrap &&
        KONG_DATABASE=cassandra kong migrations bootstrap

  kong:
    build: .
    image: rucciva/kong-plugin-oauth2-token-audience
    restart: unless-stopped
    depends_on: 
      migrator:
        condition: service_started
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=postgres
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_TRUSTED_IPS=0.0.0.0/0,::/0
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
    volumes:
      - ./volumes/kong/usr/local/share/lua/5.1:/usr/local/share/lua/5.1
      - ./volumes/kong/prefix:/prefix

  busted:
    build: .
    image: rucciva/kong-plugin-oauth2-token-audience
    depends_on: 
      migrator:
        condition: service_started
    environment:
      - SPEC_KONG_PG_HOST=postgres
      - SPEC_KONG_PG_DATABASE=kong
      - SPEC_KONG_CASSANDRA_CONTACT_POINTS=cassandra
      - SPEC_KONG_CASSANDRA_DATA_CENTERS=DC1:1
      - SPEC_KONG_CASSANDRA_REPL_STRATEGY=NetworkTopologyStrategy
      - SPEC_KONG_CASSANDRA_LOCAL_DATACENTER=DC1
      - SPEC_KONG_LOG_LEVEL=info
      - SPEC_KONG_DNS_RESOLVER=
      - SPEC_KONG_PROXY_ACCESS_LOG=/proc/1/fd/1
      - SPEC_KONG_PROXY_ERROR_LOG=/proc/1/fd/2
      - SPEC_KONG_ADMIN_ACCESS_LOG=/proc/1/fd/1
      - SPEC_KONG_ADMIN_ERROR_LOG=/proc/1/fd/2
    volumes:
      - ./kong/plugins/oauth2-token-audience:/usr/local/src/kong/kong/plugins/oauth2-token-audience
      - ./spec/oauth2-token-audience:/usr/local/src/kong/spec/oauth2-token-audience
      # - ./volumes/busted/usr/local/src/kong/servroot:/usr/local/src/kong/servroot
    working_dir: /usr/local/src/kong/
    command: bin/busted -v spec/oauth2-token-audience